### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'name' ?

### ISSUE THREAD

**Issue by ajoldham** [freimer/import-pan#5]
xxx# python import.py  -p 192.168.55.10 -u admin -P admin
resource "panos_address_object" "addr2" {
  name  = "addr2"
  type  = "ip-netmask"
  value = "1.1.1.1"
}

resource "panos_address_object" "test4" {
  name  = "test4"
  type  = "ip-netmask"
  value = "4.4.4.4"
}

Traceback (most recent call last):
  File "import.py", line 274, in <module>
    main()
  File "import.py", line 269, in main
    parse_address_group()
  File "import.py", line 155, in parse_address_group
    values = object_header(o, 'panos_address_group', 'panos_panorama_address_group')
  File "import.py", line 100, in object_header
    return generic_header(o, panos_resource_type, panorama_resource_type, objects)
  File "import.py", line 86, in generic_header
    if o.name in t:
AttributeError: 'NoneType' object has no attribute 'name'
xxx:/#

Any ideas? :)

Thx!

**Comment by ajoldham** [comment]
Figured it out... just turns out my FW didn't have any Address-Groups  :) ... Added one and all is good.  Nice script, thx!!! :)
